version: '2'

services:
  redmine:
    image: sameersbn/redmine:3.3.2-1
    environment:
      - DB_ADAPTER=postgresql
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production
      - REDMINE_PORT=10083
      - REDMINE_HTTPS=false
    ports:
      - 10083:80
    depends_on:
      - postgresql
    restart: always

  postgresql:
    image: sameersbn/postgresql:9.6-2
    environment:
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_production
      - PG_PASSWORD=password
    restart: always
    ports:
      - 5432:5432
